# Site settings
title: Mantis | 动如脱兔
description: "Make coding easier."
url: ""
author:
  name: "SpringLo"
  email: "springlo@126.com"
  url: "https://github.com/springlo"

# Build settings
baseurl: / #/emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
gems: [jekyll-paginate]
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "0.1.2"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
